# -*- coding: utf-8 -*-
"""LIMPEZA_CANDIDATOS_CANDIDATURA_PARTIDO_ELEICAO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oN2moTDZO1Q0yn0T35pI1ZpCqEMrwet1
"""

import pandas as pd

df = pd.read_csv('/content/Candidatos.csv')

df.head()

df.info()

df.shape

df.columns

df.groupby('situacao').size()

df.groupby(['ano','id_eleicao','tipo_eleicao']).size()

"""**Limpar base para conter apenas:**

*   deferido
*   deferido com recurso


"""

df_deferido = df[(df['situacao'] == 'deferido') | (df['situacao'] == 'deferido com recurso')]

df_deferido.reset_index(inplace=True)

df_deferido = df_deferido.drop(columns=['index'])

df_deferido

df_deferido[['numero', 'nome_urna','numero_partido','nome']]

# 1. Ajuste para tabela do BD
mapeamento = {
    "sequencial": "sequencial_candidato",
    "titulo_eleitoral": "titulo_eleitoral",
    "id_eleicao": "id_eleicao",
    "numero_partido": "numero_partido",
    "id_municipio": "id_municipio",
    "cargo": "cargo",
    "numero": "numero_urna",
    "nome_urna": "nome_urna",
    "situacao": "situacao"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las
df_deferido_tabela = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).copy()


# Visualizar o resultado
df_deferido_tabela.head()

df_deferido_tabela.to_csv('candidatos.csv', index=False)

# 1. Ajuste para tabela do BD
mapeamento = {
    "titulo_eleitoral": "titulo_eleitoral",
    "cpf": "cpf",
    "nome": "nome",
    "data_nascimento": "data_nascimento",
    "genero": "genero",
    "raca": "raca"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las
df_deferido_pessoas = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).copy()


# Visualizar o resultado
df_deferido_pessoas.head()

df_deferido_pessoas.to_csv('pessoas.csv', index=False)

# 1. Ajuste para tabela do BD
mapeamento = {
    "id_eleicao": "id_eleicao",
    "ano": "ano",
    "tipo_eleicao": "tipo_eleicao",
    "data_eleicao": "data_eleicao"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las

df_deferido_eleicao = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).drop_duplicates().copy()
df_deferido_eleicao.reset_index(inplace=True)
df_deferido_eleicao = df_deferido_eleicao.drop(columns=['index'])

# Visualizar o resultado
df_deferido_eleicao.head()

df_deferido_eleicao.to_csv('eleicao.csv', index=False)

# 1. Ajuste para tabela do BD
mapeamento = {
    "numero_partido": "numero_partido",
    "sigla_partido": "sigla_partido"
}

# 2. Filtrar apenas as colunas desejadas e renomeá-las

df_deferido_partido = df_deferido[list(mapeamento.keys())].rename(columns=mapeamento).drop_duplicates().copy()
df_deferido_partido.reset_index(inplace=True)
df_deferido_partido = df_deferido_partido.drop(columns=['index'])

# Visualizar o resultado
df_deferido_partido.head()

df_deferido_partido.to_csv('partido.csv', index=False)